"""Generation of EnforceGate ``.policy`` files.

Each feed becomes a single-rule policy whose name is the feed's ``slug``
(e.g. ``ut1-adult``, ``abusech-urlhaus``) so it is clearly attributed in the
engine's audit log. The rule points at the feed's domain list via
``match-domain-list`` and carries the description as the explanation text.
"""

from __future__ import annotations

from pathlib import Path

from .categories import Action, Category

# Upstream attribution per source, shown in the generated policy header.
_SOURCE_ATTRIBUTION = {
    "ut1": "https://dsi.ut-capitole.fr/blacklists/  (CC BY-SA 4.0)",
    "abusech": "https://urlhaus.abuse.ch/  (abuse.ch; see their terms of use)",
}


def render_policy(
    category: Category,
    *,
    list_path: Path,
    action: Action,
) -> str:
    """Render the complete ``.policy`` file text for *category*.

    Args:
        category: the feed being rendered.
        list_path: absolute path to the domain list, as the engine will
            see it (i.e. inside the shared volume).
        action: the resolved action for this feed.
    """
    source = _SOURCE_ATTRIBUTION.get(category.source, category.source)
    description = _sanitise(category.description)
    return (
        "# Auto-generated by EGGuard — do not edit by hand.\n"
        f"# Source: {source}\n"
        "# Regenerate with: egguard update\n"
        f"# Category: {category.name}\n"
        "\n"
        f"{category.slug}: {{\n"
        f"    match-domain-list: {list_path}\n"
        f"    application: https\n"
        f"    action: {action.value}\n"
        f"    description: {description}\n"
        "}\n"
    )


def _sanitise(text: str) -> str:
    """Strip characters that would break a single-line policy value."""
    return text.replace("\n", " ").replace("{", "(").replace("}", ")").strip()
