"""Generation of EnforceGate ``.policy`` files.

Each category becomes a single-rule policy whose name is ``ut1-<category>``
so it is clearly attributed in the engine's audit log. The rule points at
the category's domain list via ``match-domain-list`` and carries the
category description as the captive-portal explanation text.
"""

from __future__ import annotations

from pathlib import Path

from .categories import Category, Disposition

_HEADER = (
    "# Auto-generated by EgGuard — do not edit by hand.\n"
    "# Source: https://dsi.ut-capitole.fr/blacklists/  (CC BY-SA 4.0)\n"
    "# Regenerate with: egguard refresh\n"
)


def render_policy(
    category: Category,
    *,
    list_path: Path,
    action: Disposition,
) -> str:
    """Render the complete ``.policy`` file text for *category*.

    Args:
        category: the category being rendered.
        list_path: absolute path to the domain list, as the engine will
            see it (i.e. inside the shared volume).
        action: the resolved action for this category.
    """
    description = _sanitise(category.description)
    return (
        f"{_HEADER}"
        f"# Category: {category.name}\n"
        f"\n"
        f"ut1-{category.name}: {{\n"
        f"    match-domain-list: {list_path}\n"
        f"    application: https\n"
        f"    action: {action.value}\n"
        f"    description: {description}\n"
        f"}}\n"
    )


def _sanitise(text: str) -> str:
    """Strip characters that would break a single-line policy value."""
    return text.replace("\n", " ").replace("{", "(").replace("}", ")").strip()
